### ISSUE TITLE
[dev] .twig files support for indexing used translations

### ISSUE THREAD

**Issue by kalessil** [kalessil/yii2inspections#13]

**Comment by brandonkelly** [comment]
This will include `.html.twig` right?

**Comment by kalessil** [comment]
Correct

**Comment by kalessil** [comment]
Ready.

**Comment by carlcs** [comment]
Would it be possible to index all files associated with Twig language via “Registered Patterns” in Preferences > Editor > File Types? It is quite common to use .html extension for Twig files, SensioLabs and P&T use .html in the documentation and code base.
