### ISSUE TITLE
[idea] parametrised messages - validate provided parameters array

### ISSUE THREAD

**Issue by kalessil** [kalessil/yii2inspections#16]
Report if some parameters are missing. Pattern: parameters provides as inline array.

**Comment by brandonkelly** [comment]
Make sure you read through the full [Message Formatting](http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#message-formatting) documentation before working on this ;) Lots of different possible syntaxes to watch out for.

**Comment by kalessil** [comment]
Thank you @brandonkelly, according to docs this idea might stay just an idea...

**Comment by kalessil** [comment]
Yep, it's too complicated for implementation. Closing.
