### ISSUE TITLE
[bug] Triggers auto-complete popup when a semi-colon is typed

### ISSUE THREAD

**Issue by nvlad** [kalessil/yii2inspections#19]
https://github.com/nvlad/yii2support/issues/2

I`m use next code
```Java
@Override
public boolean invokeAutoPopup(@NotNull PsiElement position, char typeChar) {
    if (typeChar == '\'' || typeChar == '"') {
        if (position instanceof LeafPsiElement && (position.getText().equals("$category") || position.getText().equals("$message"))) {
            return true;
        }
        if (position.getNextSibling() instanceof ParameterList || position.getParent() instanceof MethodReference) {
            return true;
        }
    }

    return false;
}
```

**Comment by kalessil** [comment]
@nvlad, I can not reproduce this. Would you please provide a code fragment/step by step instructions?

I checked the solution from you, but don;t get the root case...

**Comment by nvlad** [comment]
![image](https://cloud.githubusercontent.com/assets/2493052/21945232/2b7a8d06-d9eb-11e6-9f32-0bcc5120bb01.png)

type `Yii::t('yii', '(not set)')` and add semi-colon after

**Comment by kalessil** [comment]
Confirmed, thank you for details.
