### ISSUE TITLE
Infinite indexing on PhpStorm

### ISSUE THREAD

**Issue by Sergi0Limit** [kalessil/yii2inspections#23]
After installing and switching on this plugin phpstorm has infinity indexing on startup.
Only force quit can stop this(
After switching off it all is ok. Indexing started and finished.

macOs 10.12.3
PhpStorm 2016.3
Plugin 1.0.0

PS: Project doesn't have php code. Plugin needed for other project.

**Comment by kalessil** [comment]
The plugin also indexes twig- and html-files, but still not clear why the indexing doesn't stop.

Is it possible to provide a link to the project for you?

**Comment by Sergi0Limit** [comment]
i'm not sure what you mean. My project is private and it has no link.
Project contains angularjs, html templates and multiple js files
Gulp and multiple npm modules. Maybe it this problem?

**Comment by kalessil** [comment]
I think there is a html-file in the project which the plugin keeps indexing.

Are you allowed to send html files from the project by e-mail?

**Comment by Sergi0Limit** [comment]
Maybe it has debug mode. It showed what file is inspecting now or something other...

**Comment by kalessil** [comment]
I'll build a debug version, and get back to you ~Monday with more installation instructions and details where to look for logs.

**Comment by Sergi0Limit** [comment]
Thanks)

**Comment by kalessil** [comment]
Update: it seems that I can reproduce something similar with Magento2 master, checking this.

**Comment by Sergi0Limit** [comment]
yes, same problem.

http://prntscr.com/e5bdow

and i have multiple files in ~/Library/Logs/PhpStorm2016.3/threadDumps-20170206-204913-PS-163.10504.2/20170206-204930/

e.g
[threadDump-20170206-205554.txt](https://github.com/kalessil/yii2inspections/files/755577/threadDump-20170206-205554.txt)

**Comment by kalessil** [comment]
[Fixed](https://github.com/kalessil/yii2inspections/commit/b924ba9aca2a1d1de98e64d6898567ad764b3eb9#diff-6c91fe43349225fb720f3f782f3a91b8L43)
