### ISSUE TITLE
Missing translation inspection cache bug

### ISSUE THREAD

**Issue by samdark** [kalessil/yii2inspections#24]
1. Run missing translations inspection on a project A where translation are missing.
2. Switch to project B.
3. Run missing translations inspection on a project B.
4. Issues from project A are reported. Quickfix adds missing translations from totally unrelated project.

**Comment by kalessil** [comment]
I need some input:
- Which PhpStorm is it?
- How do you switch between them (reopen, switch window or this probably multiple projects in one window)?

**Comment by samdark** [comment]
PhpStorm 2017.1.4
Build #PS-171.4694.2, built on May 16, 2017

Switching via File → Open Recent.

**Comment by kalessil** [comment]
Can not reproduce, getting thru codebase to see any suspicious fragments.

**Comment by kalessil** [comment]
Closing as was not able to reproduce
