### ISSUE TITLE
Missing @property annotations - false positives

### ISSUE THREAD

**Issue by andris-sevcenko** [kalessil/yii2inspections#25]
This inspection triggers for properties inferred from `setSomething()` method names, even if the methods are not setter methods - they take more than one parameter, and all are required.

<img width="568" alt="screen shot 2018-02-28 at 18 13 07" src="https://user-images.githubusercontent.com/1891118/36804639-104efcb8-1cb3-11e8-816f-5b0550dc4b83.png">
<img width="431" alt="screen shot 2018-02-28 at 18 12 34" src="https://user-images.githubusercontent.com/1891118/36804640-107fede6-1cb3-11e8-8cd7-acfbbfebd217.png">

**Comment by kalessil** [comment]
Got it, will check what happens - at least we need to take into account filter parameters amount.

**Comment by kalessil** [comment]
Fixed
