### ISSUE TITLE
Loosen up the regex for `|t()` for Twig template translations

### ISSUE THREAD

**Issue by khalwat** [kalessil/yii2inspections#28]
It'd be great if the "Add missing Translations" inspection worked with any combination of the following for Twig templates:

`"somestring"|t("somecat")`
`"somestring" |t("somecat")`
`"somestring" | t("somecat")`

In other words, being agnostic about whitespace before/after the `|` -- I found that I wrote my translations like this in Twig:

`"somestring" |t("somecat")`

...and it didn't pick any of them up. Took me some time to figure out what was going on!

Thanks for reading, and also for the plugin!

**Comment by kalessil** [comment]
Thank you @khalwat, will be fixed in the next release.

**Comment by brandonkelly** [comment]
Probably also worth checking for `translate` instead of `t` as they are aliases.

**Comment by kalessil** [comment]
Fixed!
