### ISSUE TITLE
Suggestion: Detect null return param

### ISSUE THREAD

**Issue by juanmacias** [kalessil/yii2inspections#30]
When a method has a return type (not null allowed), check if there is any return null inside the method.

![screen shot 2018-05-20 at 11 54 24](https://user-images.githubusercontent.com/4797797/40282406-212afbbc-5c6f-11e8-976c-a447c58161d1.png)

**Comment by brandonkelly** [comment]
This seems more like a job for [phpinspectionsea](https://github.com/kalessil/phpinspectionsea) ;)

**Comment by juanmacias** [comment]
yes, wrong project... sorry
