### ISSUE TITLE
Multiple insert of same properties when project has more than one DB

### ISSUE THREAD

**Issue by Insolita** [kalessil/yii2inspections#35]
Seems properties are detected from databases (data-sources) that used in project. I have 4 data-sources with similar structure, local, testing,staging and production and each property inserted 4 times after apply "fix missing properties". It will be good if plugin will got ability to setup concrete db/connection

**Comment by kalessil** [comment]
Question: which properties do you mean (currently there is no DB integration at all)?

**Comment by Insolita** [comment]
Hmm, probably i confused with another plugin functional But how it detect missing properties ?

**Comment by kalessil** [comment]
I'm confused now, any chance to see a screenshot demonstrating the un-desired behaviour?

**Comment by Insolita** [comment]
https://youtu.be/VNglmSvSu60

**Comment by kalessil** [comment]
Checked, that's coming from the Yii2 Support plugin by @nvlad
