### ISSUE TITLE
Use @property-read or @property-write when appropriate

### ISSUE THREAD

**Issue by brandonkelly** [kalessil/yii2inspections#39]
Currently the plugin has the ability to add `@property` annotations to classes' docblocks, based on whether a `getX()` and/or `setX()` method exists.

I’d like that to be taken a step further:

- If only a `getX()` method exists, create a `@property-read` tag.
- If only a `setX()` method exists, create a `@property-write` tag.
- If both exist, go with `@property` (as it does already).

**Comment by kalessil** [comment]
Done! I'll upload a new release to JB plugins repository today (moderation can take a few days).

**Comment by brandonkelly** [comment]
Thanks!!
