### ISSUE TITLE
[dev] Bug-fixing and Documentation

### ISSUE THREAD

**Issue by kalessil** [kalessil/yii2inspections#5]
- [x] Tests for inspections;
- [x] Bug-fixes;
- [x] Documentation: how to build the project, links to plugin development documentation;

**Comment by kalessil** [comment]
@brandonkelly: we have the second beta version, which is ready for use (installation process slightly changed for .jar from the repository). 

Would you please update the plugin and try working with it until end of week?

**Comment by brandonkelly** [comment]
@kalessil Just updated and looks like indexing finished successfully. No errors this time. I'll start working with the inspections today.

**Comment by kalessil** [comment]
Sounds good as for me )

**Comment by kalessil** [comment]
Heh, we got a great plugin ID: https://plugins.jetbrains.com/phpstorm/plugin/9400-yii2-inspections

**Comment by kalessil** [comment]
Closing the issue, the plugin left beta-phase.
