### ISSUE TITLE
Usage of non-English in Yii::t()

### ISSUE THREAD

**Issue by samdark** [kalessil/yii2inspections#6]
It is recommended to use either English or ASCII keys as translation sources. Usage of any characters out of ASCII range will cause translation problems later.

```php
Yii::t('user', 'Hello!'); // correct
Yii::t('user', 'hell-o'); // correct
Yii::t('user', 'Привет!'); // incorrect
```

**Comment by brandonkelly** [comment]
@samdark Ah, right, just translation process complications, not technical ones :)

**Comment by samdark** [comment]
Yes.

**Comment by kalessil** [comment]
Should it be highlighted as a weak warning, warning or an error?

**Comment by samdark** [comment]
Weak warning should be enough.

**Comment by kalessil** [comment]
Added, can be deactivated in options.
