### ISSUE TITLE
[dev] craft\web\View::registerTranslations('category', ['', ...])

### ISSUE THREAD

**Issue by kalessil** [kalessil/yii2inspections#7]
- [x] Apply "Translation message correctness" inspection to the translations array
- [ ] Register translations from the array as used while indexing

**Comment by kalessil** [comment]
@samdark: does anything like this exist in Yii2?

**Comment by samdark** [comment]
No, not really. That's custom.

**Comment by brandonkelly** [comment]
Yeah Yii doesn't have a major front-end framework built in (nor should it), so it doesn't need to worry about how to register translation messages for Javascript use.

**Comment by brandonkelly** [comment]
**Feature description:**

If the project contains a `craft\web\View` class, the plugin should find calls to its `registerTranslations()` method, and index each of translation messages passed into the `$messages` argument (array), with the `$category` argument (string) as the translation category.
