### ISSUE TITLE
[dev] {% do view.registerTranslations('category', ['', ...]) %}

### ISSUE THREAD

**Issue by kalessil** [kalessil/yii2inspections#8]

**Comment by kalessil** [comment]
Closing, as this wasn't picked up for further development.

**Comment by brandonkelly** [comment]
I'm not *against* doing this, but I think we should prioritize #7

**Comment by kalessil** [comment]
oops ), reopening

**Comment by brandonkelly** [comment]
@kalessil If you're done with #7 and there's still time left, would be great to have this implemented :)

**Comment by kalessil** [comment]
Okay. I also think that I could make 1 maybe 2 additional inspections, do you have more ideas?
